### ISSUE TITLE
Day 3 almost over and still no notebook was pushed?

### ISSUE THREAD

**Issue by antoine-palazz** [senshastic/advent-of-code-2024#1]
Can't wait to see your solution for today's problem!

**Comment by senshastic** [comment]
I wholeheartedly recommend subscribing to SneshPremium for earlier than last minute commits 🤪

**Comment by antoine-palazz** [comment]
plz send link

**Comment by FallenStar08** [comment]
hi hello welcome bonjour where is le day trois de today??? thanks

**Comment by senshastic** [comment]
Hi hello welcome bonjour le day 3 was published for my fans, tomorrow I'll do it even later
